# 以下为必填项
# 你的 Bot Token
BOT_TOKEN = YOUR_BOT_TOKEN

# 你的网易云 cookie 中 MUSIC_U 项的值（用于下载无损歌曲）
MUSIC_U = YOUR_MUSIC_U

# 以下为可选项
# 自定义 telegram bot API 地址
BotAPI = http://bot-api:8081

# 设置 bot 管理员 ID, 用 “,” 分隔
BotAdmin = 115414,1919810

# 是否开启 bot 的 debug 功能
BotDebug = false

# 自定义 sqlite3 数据库文件（默认为 cache.db）
Database = cache/cache.db

# 设置日志等级 [panic|fatal|error|warn|info|debug|trace] (默认为 info)
LogLevel = info

# 下载超时时长 (单位秒, 默认为 60)
DownloadTimeout = 60

# 自定义下载反向代理
ReverseProxy = 114.5.1.4:8080
